[build]
  command = "npx pnpm i --store=node_modules/.pnpm-store --no-frozen-lockfile && npx next build"
  publish = ".next"
[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS="--version" # prevent npm install

[[redirects]] # https://stackoverflow.com/questions/58065603/netlify-renders-404-on-page-refresh-using-react-and-react-router
  from = "/*"
  to = "/"
  status = 200
